### ISSUE TITLE
你好运行react-native run-ios报错，请问怎么解决啊？

### ISSUE THREAD

**Issue by JserJser** [wuyunjiang/RNInitProject#1]
报错为
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNInitProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNInitProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Promise.then (/Users/liuchang/517box/RNInitProject/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)

**Comment by wuyunjiang** [comment]
我只在安卓上面运行成功，ios没测试过
